version: "3.8"

services:
  frontend:
    image: react-frontend
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: springboot-backend
    build:
      context: ./springboot-backend
    ports:
       - "8080:8080"

